name: build mount-zip

on: push

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: install deps
        run: |
          brew update
          brew install boost
          brew cask install osxfuse

      - name: build
        run: |
          make